package com.souflow.common.exception;

public enum ErrorCode {
  VALIDATION_ERROR("VALIDATION_ERROR"),
  RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND"),
  DUPLICATE_RESOURCE("DUPLICATE_RESOURCE"),
  UNAUTHORIZED("UNAUTHORIZED"),
  FORBIDDEN("FORBIDDEN"),
  BAD_REQUEST("BAD_REQUEST"),
  INTERNAL_ERROR("INTERNAL_ERROR"),
  INSUFFICIENT_STOCK("INSUFFICIENT_STOCK"),
  CART_EXPIRED("CART_EXPIRED"),
  ORDER_EXPIRED("ORDER_EXPIRED"),
  ACCOUNT_DISABLED("ACCOUNT_DISABLED");

  private final String code;

  ErrorCode(String code) {
    this.code = code;
  }

  public String getCode() {
    return code;
  }
}
