name: Spring Boot CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"] # Kích hoạt kiểm tra khi có ai tạo Pull Request vào nhánh main

jobs:
  # =============================================================
  # JOB 1: KIỂM TRA CHUẨN VIẾT COMMIT (COMMIT LINT)
  # =============================================================
  commit-lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./soulflow-api

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Lấy toàn bộ lịch sử commit để quét

      - name: Check Commit Message Style
        uses: wagoid/commitlint-github-action@v5

  # =============================================================
  # JOB 2: KIỂM TRA CHẤT LƯỢNG CODE VÀ BUILD THỬ
  # =============================================================
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up môi trường JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven # Bật cache để những lần build sau nhanh hơn

      - name: Cấp quyền chạy file Maven Wrapper
        run: chmod +x mvnw

      - name: Chốt chặn 1 - Kiểm tra Format Code (Spotless)
        run: ./mvnw spotless:check
        # Nếu có ai cố tình sửa code sai format ở local rồi push lên, bước này sẽ báo lỗi ĐỎ và dừng build.

      - name: Chốt chặn 2 - Kiểm tra đặt tên & Code Style (Checkstyle)
        run: ./mvnw checkstyle:check
        # Nếu đặt tên sai chuẩn cú pháp, bước này sẽ chặn đứng lại.

      - name: Chốt chặn 3 - Build thử ra file .jar hoàn chỉnh
        run: ./mvnw clean package -DskipTests
        # Bước cuối cùng để đảm bảo code không bị lỗi logic biên dịch.
